# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run Snp Pileup
#'
#' This function runs snp_pileup
#'
#' @param debug A logical Value. If TRUE will print 'debug' statements.
#' @return None.
#' @export
run_snp_pileup_logic <- function(input_args) {
    invisible(.Call(`_facets_run_snp_pileup_logic`, input_args))
}

#' Check Htslib Version
#'
#' This function prints the version of HTSLIB being used for snp-pileup
#'
#' @return None.
#' @export
htslib_version <- function() {
    invisible(.Call(`_facets_htslib_version`))
}

